# Generated by Django 5.2.7 on 2025-10-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('profile', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('tire_type', models.CharField(choices=[('passenger', 'Легковий'), ('truck', 'Вантажний'), ('sport', 'Спортивна')], max_length=50)),
                ('season', models.CharField(choices=[('summer', 'Літня'), ('winter', 'Зимова'), ('all_season', 'Всесезонна')], max_length=50)),
                ('load_index', models.IntegerField()),
                ('speed_index', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='tire_images/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Tier',
                'verbose_name_plural': 'Tires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand'], name='tires_tire_brand_2a9902_idx'), models.Index(fields=['season'], name='tires_tire_season_13e658_idx'), models.Index(fields=['slug'], name='tires_tire_slug_77cb3e_idx')],
            },
        ),
    ]
