# Generated by Django 5.2.7 on 2025-10-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('diameter', models.IntegerField()),
                ('width', models.IntegerField()),
                ('pcd', models.CharField(max_length=20)),
                ('dia', models.DecimalField(decimal_places=1, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='disk_images/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Disk',
                'verbose_name_plural': 'Disks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand'], name='disks_disk_brand_12a052_idx'), models.Index(fields=['diameter'], name='disks_disk_diamete_99863a_idx'), models.Index(fields=['slug'], name='disks_disk_slug_415f3d_idx')],
            },
        ),
    ]
